name: crypticdash
description: "Cryptic Dashboard - Manage multiple GitHub projects with todo lists"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI and Theming
  cupertino_icons: ^1.0.2
  
  # State Management
  provider: ^6.1.1
  
  # HTTP and API
  http: ^1.5.0
  dio: ^5.4.0
  
  # GitHub API
  github: ^9.25.0
  
  # Markdown Processing
  markdown: ^7.2.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # File Operations
  path_provider: ^2.1.1
  
  # UI Components
  url_launcher: ^6.2.1
  
  # Utilities
  intl: ^0.18.1
  crypto: ^3.0.3
  
  # Animation
  image_sequence_animator: 2.0.0
  
  # OAuth Authentication
  flutter_dotenv: ^5.1.0
  
  # AI Model Support
  json_annotation: ^4.8.1
  onnxruntime: ^1.4.1
  
  # In-App Purchase
  in_app_purchase: ^3.1.13
  
  # Stripe Integration
  stripe_platform_interface: ^12.0.0
  stripe_android: ^12.0.1
  stripe_ios: ^12.0.1
  url_launcher_web: ^2.4.1
  
  # Utilities
  uuid: ^4.5.1
  logger: ^2.6.1
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/ai_models/gemma_3_270m_it/
    - assets/yeti_animation/
    - TODO_TEMPLATE.md
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/crypticdash.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1976D2"
  adaptive_icon_foreground: "assets/images/crypticdash.png"
  web:
    generate: true
    image_path: "assets/images/crypticdash.png"
    background_color: "#1976D2"
    theme_color: "#1976D2"
  windows:
    generate: true
    image_path: "assets/images/crypticdash.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/crypticdash.png"
  linux:
    generate: true
    image_path: "assets/images/crypticdash.png"
